name = "cheelee_bd_bot"
main = "src/index.ts"
compatibility_date = "2025-09-07"


# We’ll store secrets via `wrangler secret put`, not here.
# If you want a custom route on your domain, also add a routes section.